{% set name = "qforce" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qforce-{{ version }}.tar.gz
  sha256: 255e3c58c33548802aae034b83b2ac53fa43c26edee634c21373efb55fc24368

build:
  entry_points:
    - qforce=qforce.main:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - ase
    - matplotlib-base
    - networkx
    - numba >=0.50
    - numpy
    - pulp <2.2
    - pycolt >=0.5.3
    - python >=3.6
    - scipy
    - seaborn

test:
  imports:
    - qforce
  commands:
    - pip check
    - qforce --help
  requires:
    - pip

about:
  home: https://github.com/selimsami/qforce
  summary: 'Q-Force: Quantum mechanically augmented molecular force fields'
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jan-janssen
