{% set name = "qforce" %}
{% set version = "0.6.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qforce-{{ version }}.tar.gz
  sha256: 8f5e5c8f174f2a4a3468e6d2d973bd56494e9233db9c99a122f8a36ea2f1a01b

build:
  entry_points:
    - qforce=qforce.main:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - ase
    - matplotlib-base
    - networkx
    - numba >=0.50
    - numpy
    - pulp <2.2
    - pycolt >=0.5.3
    - python >=3.6
    - scipy
    - seaborn

test:
  imports:
    - qforce
  commands:
    - pip check
    - qforce --help
  requires:
    - pip

about:
  home: https://github.com/selimsami/qforce
  summary: 'Q-Force: Quantum mechanically augmented molecular force fields'
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jan-janssen
